import { base, browserName, launch } from './browser-env.mjs';
import assert from 'node:assert/strict';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openSync, ftruncateSync, closeSync, unlinkSync } from 'node:fs';

const browser = await launch();
let assertions = 0;
const check = (condition, message) => { assert.ok(condition, message); assertions++; };
try {
  for (const [width, height] of [[360, 800], [390, 844], [768, 900], [1280, 900]]) {
    const page = await browser.newPage({ viewport: { width, height } });
    await page.goto(base);
    if (width === 390 || width === 1280) await page.screenshot({ path: join(tmpdir(), `json-to-html-empty-${width}.png`), fullPage: true });
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `horizontal scroll at ${width}`);
    await page.locator('#try-example').click();
    await page.locator('#convert').click();
    await page.locator('#result:not([hidden])').waitFor();
    check(await page.locator('#result-summary').textContent().then(x => x.includes('3 rows')), `example conversion at ${width}`);
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `result horizontal scroll at ${width}`);
    if (width === 390 || width === 1280) await page.screenshot({ path: join(tmpdir(), `json-to-html-${width}.png`), fullPage: true });
    await page.close();
  }
  const clipboard = browserName === 'chromium';
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, acceptDownloads: true, ...(clipboard ? { permissions: ['clipboard-read', 'clipboard-write'] } : {}) });
  const page = await context.newPage();
  const requests = [];
  page.on('request', request => requests.push(`${request.method()} ${request.url()}`));
  await page.goto(base);
  await page.locator('#convert').click();
  check((await page.locator('#status').textContent()).includes('Paste some JSON'), 'empty error announced');
  check(await page.locator('#status').getAttribute('aria-live') === 'polite', 'live status region');
  await page.locator('#json-input').fill('{\n  "a": 1,\n}');
  await page.locator('#convert').click();
  await page.waitForFunction(() => document.querySelector('#status')?.textContent?.includes('Line 2'));
  check((await page.locator('#status').textContent()).includes('Line 2, column 9'), 'error position');
  check(await page.locator('#json-input').evaluate(el => el instanceof HTMLTextAreaElement && el.selectionStart === el.selectionEnd), 'error caret');
  await page.locator('#json-input').fill('{"a":1}\n{"a":2}');
  await page.locator('#convert').click();
  await page.locator('#json-lines-help:not([hidden])').waitFor();
  await page.locator('#wrap-lines').click();
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  check((await page.locator('#result-summary').textContent()).includes('2 rows'), 'JSON Lines wrap');
  await page.locator('#try-example').click();
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  await page.locator('[data-view="code"]').click();
  check(await page.locator('#code-view').isVisible(), 'code chip');
  check((await page.locator('#code-view').textContent()).includes('<table>'), 'code content');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'code view stays within page');
  const actualSize = await page.locator('#code-view').evaluate(el => new Intl.NumberFormat('en', { maximumFractionDigits: 1 }).format(new Blob([el.textContent || '']).size / 1024) + ' KB');
  check((await page.locator('#result-summary').textContent()).includes(actualSize), 'displayed byte size matches Blob');
  await page.locator('[data-view="preview"]').click();
  check(await page.locator('#preview-frame').isVisible(), 'preview chip');
  check(await page.locator('#preview-frame').getAttribute('sandbox') === '', 'sandboxed preview');
  await page.locator('[data-layout="list"]').click();
  await page.waitForFunction(() => document.querySelector('#code-view')?.textContent?.includes('<dl>'));
  check((await page.locator('#convert').textContent()).includes('list'), 'list chip and button label');
  await page.locator('[data-output="page"]').click();
  await page.waitForFunction(() => document.querySelector('#code-view')?.textContent?.startsWith('<!doctype html>'));
  check((await page.locator('#code-view').textContent()).startsWith('<!doctype html>'), 'full page chip');
  await page.locator('#copy').click();
  if (clipboard) {
    await page.waitForFunction(() => document.querySelector('#copy')?.textContent === 'Copied');
    check((await page.locator('#copy').textContent()) === 'Copied', 'copy action');
    check((await page.evaluate(() => navigator.clipboard.readText())).startsWith('<!doctype html>'), 'clipboard contents');
  } else {
    await page.waitForFunction(() => document.querySelector('#copy')?.textContent === 'Copied' || getSelection()?.toString().startsWith('<!doctype html>'));
    check(true, 'copy action or selection fallback');
  }
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#download').click()]);
  check(download.suggestedFilename() === 'converted.html', 'pasted download name');
  const file = { name: 'orders.json', mimeType: 'application/json', buffer: Buffer.from('[{"id":1}]') };
  await page.locator('#json-file').setInputFiles(file);
  await page.waitForFunction(() => document.querySelector('#file-name')?.textContent === 'orders.json');
  check((await page.locator('#file-size').textContent()).includes('bytes'), 'file name and size');
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  const [fileDownload] = await Promise.all([page.waitForEvent('download'), page.locator('#download').click()]);
  check(fileDownload.suggestedFilename() === 'orders.html', 'file download name');
  const largePath = join(tmpdir(), `oversize-${process.pid}.json`);
  const largeHandle = openSync(largePath, 'w');
  ftruncateSync(largeHandle, 50 * 1024 * 1024 + 1);
  closeSync(largeHandle);
  await page.locator('#json-file').setInputFiles(largePath);
  unlinkSync(largePath);
  check((await page.locator('#status').textContent()).includes('over 50 MB'), 'file size limit');
  await page.locator('#json-file').setInputFiles({ name: 'wrong.csv', mimeType: 'text/csv', buffer: Buffer.from('a,b') });
  check((await page.locator('#status').textContent()).includes('.json or .txt'), 'file type limit');
  await page.locator('#json-input').fill('{"large":9007199254740993}');
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  check((await page.locator('#code-view').textContent()).includes('9007199254740993'), 'large integer browser conversion');
  await page.evaluate(() => {
    const data = new DataTransfer();
    data.items.add(new File(['{"dropped":true}'], 'dropped.json', { type: 'application/json' }));
    document.querySelector('#json-tool').dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: data }));
    document.querySelector('#json-tool').dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: data }));
  });
  await page.waitForFunction(() => document.querySelector('#file-name')?.textContent === 'dropped.json');
  check((await page.locator('#json-input').inputValue()).includes('dropped'), 'drag and drop');
  await page.locator('#json-input').fill('[{"a":1},{"constructor":2}]');
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  await page.locator('[data-view="code"]').click();
  check(!(await page.locator('#code-view').textContent()).includes('native code'), 'inherited keys stay empty');
  await page.locator('#json-input').fill('{\n  "a": 1\n  "b": 2\n}');
  await page.locator('#convert').click();
  await page.waitForFunction(() => document.querySelector('#status')?.textContent?.includes('Line 3'));
  check((await page.locator('#status').textContent()).includes('Line 3, column 3'), 'missing comma position in this engine');
  await page.locator('#try-example').click();
  await page.locator('#convert').click();
  await page.locator('#result:not([hidden])').waitFor();
  await page.locator('#start-over').click();
  check(await page.locator('#json-input').inputValue() === '', 'start over');
  await page.locator('#json-input').blur();
  await page.keyboard.press('Tab');
  check(await page.evaluate(() => document.activeElement?.matches('a,textarea,button')), 'keyboard tab focus');
  check(await page.evaluate(() => getComputedStyle(document.activeElement).outlineStyle !== 'none'), 'visible keyboard focus');
  await page.locator('[data-layout="list"]').focus();
  await page.keyboard.press('Enter');
  check((await page.locator('#convert').textContent()).includes('list'), 'keyboard chip selection');
  check(requests.every(request => !request.startsWith('POST')), 'no user data network requests');
  const touch = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
  await touch.goto(base);
  check((await touch.locator('#input-hint').textContent()).includes('choose a file'), 'touch wording');
  await touch.close();
  const reduced = await browser.newPage({ reducedMotion: 'reduce' });
  await reduced.goto(base);
  check(await reduced.locator('#json-tool').evaluate(el => getComputedStyle(el).transitionDuration === '0s'), 'reduced motion');
  await reduced.close();
  await context.close();
  console.log(`Browser checks passed in ${browserName}: ${assertions} assertions`);
} finally { await browser.close(); }
